version: '2.4'

services:

   ansible:
     image: ansible${ANSLTAG}
     build:
       context: .
       dockerfile: Dockerfile_Ansible
     volumes:
       - ../../ansible:/etc/ansible
     command: all -m ping
     entrypoint: ansible
     mem_limit: 500m
     networks:
       - footloose-demo

networks:
  footloose-demo: 
