---
- name: render hashiui monit config
  template: src="{{hashiui_service}}.j2"
            dest="/etc/monit.d/{{hashiui_service}}"
            owner="root"
            group="root"
  notify:
    - reload monit configs

- name: start and enable monit service
  service: name=monit
           state=started
           enabled=true
