---
- name: render consul monit config
  template: src="{{consul_service}}.j2"
            dest="/etc/monit.d/{{consul_service}}"
            owner="root"
            group="root"
  notify:
    - reload monit configs

- name: start and enable monit service
  service: name=monit
           state=started
           enabled=true
