---
- name: restart consul
  service: name=consul
           state=restarted

- name: reload config
  shell: /usr/sbin/consul reload

- name: restart redis
  service: name=redis
           state=restarted
