---
- name: render goss spark test
  template: src="goss_spark_{{ spark_version }}-{{ spark_hadoop_version }}.yaml.j2"
            dest="{{ goss_binary['configad_location'] }}/goss_spark.yaml"
  notify:
    - restart goss server

