---
- name: generate gossip encryption key
  shell: "if [[ -z $(sudo grep encrypt /etc/consul.d/consul.json|awk -F': *' '{print $NF}'|sed 's/\"//g'|sed 's/,//') ]];then consul keygen;fi"
  register: gosenckey
  run_once: true

- name: render consul server configuration
  template: src="consul.json.j2"
            dest=/etc/consul.d/consul.json
            owner=root
            group=root
  when: gosenckey.stdout_lines|length > 0
  notify:
    - restart consul

- name: render consul systemd unit
  template: src="consul.service.j2"
            dest=/etc/systemd/system/consul.service
            owner=root
            group=root

- name: start and enable consul service
  service: name=consul
           state=started
           enabled=true
