version: '3.5'

services:

  monitoror:
    image: monitoror/monitoror:${MTRRTAG:-latest}
    volumes:
      - ./configs/:/etc/monitoror/
    ports:
     - "38080:8080"
    environment:
      - "MO_CONFIG=/etc/monitoror/config.json"
    restart: unless-stopped
    networks:
      - monitoror-demo

networks:
  monitoror-demo:
