---
- name: download docker compose
  get_url: url="{{ docker_packages['all']['docker_compose_dwnldurl'] }}"
           dest="{{ docker_packages['all']['docker_compose_location'] }}"
           mode='0755'
           validate_certs=no

- name: create docker compose dir
  file: path="{{ docker_packages['all']['docker_compose_dir'] }}"
        state=directory
        recurse=yes
