---
- name: add nginx repo
  yum_repository: name=nginx
                  description="nginx repository"
                  baseurl="{{nginx_base_url}}"
                  gpgcheck=no
                  enabled=yes
                  state=present
  when: ansible_virtualization_type == "virtualbox"

- name: install nginx package
  yum: name="{{package_nginx}}"
       state=present
       update_cache={{update_cache}}

- name: render nginx config
  template: src="nginx.conf.j2"
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
  notify:
    - restart nginx

- name: render htpasswd file
  template: src="htpasswd.j2"
            dest=/etc/nginx/.htpasswd
            owner=root
            group=root
  notify:
    - restart nginx

- name: render crt file
  template: src="localhost.crt.j2"
            dest=/etc/pki/tls/certs/localhost.crt
            owner=root
            group=root
  notify:
    - restart nginx

- name: render key file
  template: src="localhost.key.j2"
            dest=/etc/pki/tls/private/localhost.key
            owner=root
            group=root
  notify:
    - restart nginx

- name: put selinux permissive
  selinux: policy=targeted
           state=permissive

- name: start and enable nginx service
  service: name=nginx
           state=started
           enabled=true
