version: '2.1'

services:

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash-oss${LGSTTAG}
    container_name: logstash
    hostname: logstash
    ports:
      - "127.0.0.1:12201:12201/udp"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss${ELSTTAG}
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "19200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 800m
    restart: always
    networks:
      - rbtmq-demo

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss${KBNATAG}
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 15601:5601
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo

  consulserver:
    depends_on:
      - logstash
    image: consul${CNSLTAG}
    container_name: consulserver
    hostname: consulserver
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "consulserver"

  hashiui:
    depends_on:
      - consulserver
    image: jippi/hashi-ui${HSUITAG}
    volumes:
      - ./certs/out/:/etc/ssl/certs/
      - ./:/tmp/
    ports:
      - "23000:3000"
    environment:
      - CONSUL_ENABLE=1
      - CONSUL_READ_ONLY=1
      - CONSUL_ADDR=consulserver:8500
      - HTTPS_ENABLE=true
      - SERVER_CERT=/etc/ssl/certs/test.crt
      - SERVER_KEY=/etc/ssl/certs/test.key
    command: sh -c "/tmp/wait-for-command.sh -c 'nc -vz consulserver 8500' -s 0 && /hashi-ui"
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "hashiui"

  cnslprome:
    depends_on:
      - consulserver
    image: prom/consul-exporter${CSPETAG}
    container_name: cnslprome
    hostname: cnslprome
    command: "--consul.server=consulserver:8500"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "cnslprome"

  rbtmqcnsl:
    depends_on:
      - consulserver
    image: consul${CNSLTAG}
    container_name: rbtmqcnsl
    hostname: rbtmqcnsl
    command: "agent -retry-join consulserver -client 0.0.0.0"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmqcnsl"

  rbtmq1:
    depends_on:
      - rbtmqcnsl
    image: rabbitmq${RMQTAG}
    container_name: rbtmq1
    hostname: rbtmq1
    volumes:
      - ./conf/:/etc/rabbitmq/
      - rbtmq1-data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RMQERC:-1234567890}
    mem_limit: 1g
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmq1"

  rbtmqprome1:
    depends_on:
      - rbtmq1
    image: kbudde/rabbitmq-exporter${RBPETAG}
    container_name: rbtmqprome1
    hostname: rbtmqprome1
    environment:
      - RABBIT_URL=http://rbtmq1:15672
      - RABBIT_CAPABILITIES=bert,no_sort
      - PUBLISH_PORT=9419 
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmqprome1"

  rbtmq2:
    depends_on:
      - rbtmqcnsl
    image: rabbitmq${RMQTAG}
    container_name: rbtmq2
    hostname: rbtmq2
    volumes:
      - ./conf/:/etc/rabbitmq/
      - rbtmq2-data:/var/lib/rabbitmq
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RMQERC:-1234567890}
    mem_limit: 1g
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmq2"

  rbtmqprome2:
    depends_on:
      - rbtmq2
    image: kbudde/rabbitmq-exporter${RBPETAG}
    container_name: rbtmqprome2
    hostname: rbtmqprome2
    environment:
      - RABBIT_URL=http://rbtmq2:15672
      - RABBIT_CAPABILITIES=bert,no_sort
      - PUBLISH_PORT=9419 
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmqprome2"

  rbtmq3:
    depends_on:
      - rbtmqcnsl
    image: rabbitmq${RMQTAG}
    container_name: rbtmq3
    hostname: rbtmq3
    volumes:
      - ./conf/:/etc/rabbitmq/
      - rbtmq3-data:/var/lib/rabbitmq
    ports:
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RMQERC:-1234567890}
    mem_limit: 1g
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmq3"

  rbtmqprome3:
    depends_on:
      - rbtmq3
    image: kbudde/rabbitmq-exporter${RBPETAG}
    container_name: rbtmqprome3
    hostname: rbtmqprome3
    environment:
      - RABBIT_URL=http://rbtmq3:15672
      - RABBIT_CAPABILITIES=bert,no_sort
      - PUBLISH_PORT=9419
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmqprome3"

  rbtmqprftst:
    depends_on:
      - rbtmq1
      - rbtmq2
      - rbtmq3
    image: pivotalrabbitmq/perf-test${PRFTTAG}
    container_name: rbtmqprftst
    hostname: rbtmqprftst
    command: "--uri amqp://rbtmq1"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "rbtmqprftst"

  cadvisor:
    depends_on:
      - logstash
    image: google/cadvisor${CAVRTAG}
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "38080:8080"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "cadvisor"

  portainer:
    depends_on:
      - logstash
    image: portainer/portainer${PTNRTAG}
    container_name: portainer
    hostname: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "19000:9000"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "portainer"

  prometheus:
    depends_on:
      - logstash
    image: prom/prometheus${PROMTAG}
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "prometheus"

  grafana:
    depends_on:
      - logstash
    image: grafana/grafana${GRFNTAG}
    container_name: grafana
    hostname: grafana
    volumes:
      - ./certs/out/:/etc/ssl/certs/
      - ./datasources/:/etc/grafana/provisioning/datasources/
      - ./dashboards/conf/:/etc/grafana/provisioning/dashboards/
      - ./dashboards/:/usr/share/grafana/conf/provisioning/dashboards/
      - grafana-data:/var/lib/grafana
    ports:
      - "13000:3000"
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/ssl/certs/test.crt
      - GF_SERVER_CERT_KEY=/etc/ssl/certs/test.key
    mem_limit: 500m
    restart: always
    networks:
      - rbtmq-demo
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "grafana"

volumes:
  rbtmq1-data:
  rbtmq2-data:
  rbtmq3-data:
  portainer-data:
  grafana-data:
  elasticsearch-data:
  prometheus-data:

networks:
  rbtmq-demo:
