---
- name: turn off swap
  command: swapoff -a

- name: remove swap entry
  lineinfile: name=/etc/fstab
              regexp='swap'
              state=absent

- name: install elasticsearch package
  yum: name="{{package_elasticsearch}}"
       state=present
       update_cache={{update_cache}}

- name: get xpack archive
  yum: name="{{package_xpack}}"
       state=present
       update_cache={{update_cache}}
  when: apply_xpack

- name: gather current plugins list
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list
  register: lstplgns

- name: install xpack on elsticsearch node
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch "file:///opt/{{package_xpack}}-{{version_xpack}}.zip"
  when: apply_xpack and "x-pack" not in lstplgns.stdout_lines

- name: render elasticsearch config
  template: src="elasticsearch.yml_{{version_elasticsearch}}.j2"
            dest=/etc/elasticsearch/elasticsearch.yml
            owner=root
            group=elasticsearch
  notify:
    - restart elasticsearch

- name: render jvm.options config
  template: src="jvm.options_{{version_elasticsearch}}.j2"
            dest=/etc/elasticsearch/jvm.options
            owner=root
            group=elasticsearch
  notify:
    - restart elasticsearch

- name: ensure proper permissions for data mount
  file: path="{{path_data}}"
        owner="elasticsearch"
        group="elasticsearch"
        recurse=yes

- name: start and enable elasticsearch service
  service: name=elasticsearch
           state=started
           enabled=true

- name: cleanup xpack archive
  file: path="/opt/{{package_xpack}}-{{version_xpack}}.zip"
        state=absent
  when: apply_xpack
