version: '2.4'

services:

  prometheus:
    image: prom/prometheus${PROMTAG}
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    mem_limit: 500m
    restart: always
    networks:
      - prometheus-demo
