version: '2.4'

services:

  rustbyexample:
    image: rustbyexample:latest
    container_name: rustbyexample
    hostname: rustbyexample
    build:
      context: .
      dockerfile: Dockerfile_RustByExample
    ports:
      - "23000:3000"
    mem_limit: 500m
    networks:
      - rustbyexample-demo

networks:
  rustbyexample-demo:
