---
- name: install logstash package
  yum: name="{{package_logstash}}"
       state=present
       update_cache={{update_cache}}

- name: get xpack archive
  yum: name="{{package_xpack}}"
       state=present
       update_cache={{update_cache}}
  when: apply_xpack

- name: gather current plugins list
  command: /usr/share/logstash/bin/logstash-plugin list
  register: lstplgns

- name: install xpack on logstash node
  command: /usr/share/logstash/bin/logstash-plugin install "file:///opt/{{package_xpack}}-{{version_xpack}}.zip"
  when: apply_xpack and "x-pack" not in lstplgns.stdout_lines

- name: render logstash config
  template: src="logstash.yml_{{version_logstash}}.j2"
            dest=/etc/logstash/logstash.yml
            owner=root
            group=logstash
  notify:
    - restart logstash

- name: render filter config
  template: src="filters.conf_{{version_logstash}}.j2"
            dest=/etc/logstash/conf.d/filters.conf
            owner=root
            group=logstash

- name: port substitution in filter config
  replace: dest=/etc/logstash/conf.d/filters.conf
           regexp='ELSM_PORT'
           replace="{{http_port}}"
  notify:
    - restart logstash

- name: ensure proper permissions for data mount
  file: path="{{path_data}}"
        owner="logstash"
        group="logstash"
        recurse=yes

- name: start and enable logstash service
  service: name=logstash
           state=started
           enabled=true
