---
- name: upload agent binaries
  copy: src="{{item}}"
        dest="/opt/consul/{{item}}"
        owner="root"
        group="root"
        mode=0754
  with_items: "{{agent_binaries}}"

- name: extract gossip encryption key
  shell: grep encrypt /etc/consul.d/consul.json|awk -F'"' '{print $4}'
  delegate_to: "{{groups['server'][0]}}"
  register: gosenckey

- name: render consul client configuration
  template: src="client.json.j2"
            dest=/etc/consul.d/client.json
            owner=root
            group=root
  notify:
    - restart consul client

- name: render agents systemd units
  template: src="{{item}}.service.j2"
            dest="/etc/systemd/system/{{item}}.service"
            owner=root
            group=root
  with_items: "{{agent_services}}"

- name: start and enable agents services
  service: name="{{item}}"
           state=started
           enabled=true
  with_items: "{{agent_services}}"
