---
# https://docs.docker.com/install/linux/docker-ce/debian/

- name: update apt package index
  shell: apt-get update
  ignore_errors: yes

- name: install utility packages
  apt: name="{{docker_packages[ansible_os_family|lower]['utility']}}"
       state=present

- name: add official GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: add stable repo
  shell: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""
  ignore_errors: yes

- name: update apt package index
  shell: apt-get update
  ignore_errors: yes

- name: install main packages
  apt: name="{{docker_packages[ansible_os_family|lower]['main']}}"
       state=present

- name: start and enable docker service
  service: name=docker
           state=started
           enabled=true
