---
# https://docs.docker.com/install/linux/docker-ce/centos/

- name: install utility packages
  yum: name="{{docker_packages[ansible_os_family|lower]['utility']}}"
       state=present

# neither yum_repository nor get_url worked
- name: add stable repository
  shell: "yum-config-manager --add-repo {{docker_packages[ansible_os_family|lower]['repo']}}"

- name: install main packages
  yum: name="{{docker_packages[ansible_os_family|lower]['main']}}"
       state=present

- name: start and enable docker service
  service: name=docker
           state=started
           enabled=true
