---
- name: install kibana package
  yum: name="{{package_kibana}}"
       state=present
       update_cache={{update_cache}}

- name: get xpack archive
  yum: name="{{package_xpack}}"
       state=present
       update_cache={{update_cache}}
  when: apply_xpack

- name: gather current plugins list
  command: /usr/share/kibana/bin/kibana-plugin list
  register: lstplgns

- name: install xpack on kibana node
  command: /usr/share/kibana/bin/kibana-plugin install "file:///opt/{{package_xpack}}-{{version_xpack}}.zip"
  when: apply_xpack and "x-pack@{{version_kibana}}" not in lstplgns.stdout_lines

- name: render kibana config
  template: src="kibana.yml_{{version_kibana}}.j2"
            dest=/etc/kibana/kibana.yml
            owner=root
            group=kibana
  notify:
    - restart kibana

- name: start and enable kibana service
  systemd: name=kibana
           state=started
           daemon_reload=yes
           enabled=true

- name: poll for the http api to get ready
  wait_for: port="{{http_port}}"
            delay=10
            connect_timeout=300

#- name: upload xpack monitoring license
#  copy: src="{{package_xpack}}-{{version_xpack}}-license.json"
#        dest=/tmp
#  when: apply_xpack

- name: apply xpack monitoring license
  uri:  url="http://localhost:{{http_port}}/_xpack/license?acknowledge=true"
        method=PUT
        user=elastic
        body="{{lookup('file',"{{package_xpack}}-{{version_xpack}}-license.json")}}"
        body_format=json
  when: apply_xpack
  run_once: true

#- name: cleanup xpack monitoring license
#  file: path="/opt/{{package_xpack}}-{{version_xpack}}-license.json"
#        state=absent
#  when: apply_xpack
