version: '3.5'

services:
  cassandra:
    image: cassandra${CSATAG}
    volumes:
      - data-volume:/var/lib/cassandra
    ports:
      - "9042:9042"
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal:
    image: temporalio/server${TMLTAG}
    ports:
     - "7233:7233"
    environment:
      - "AUTO_SETUP=true"
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal-cli:
    image: temporalio/tctl${TCLTAG}
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
    entrypoint: sh
    command: "-c 'while true; do sleep 5; done'"
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal-web:
    image: temporalio/web${TWBTAG}
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
    restart: unless-stopped
    networks:
      - temporal-demo

volumes:
  data-volume:

networks:
  temporal-demo:
