version: '3.5'

services:
  cassandra:
    image: cassandra:${CSATAG:-3.11}
    volumes:
      - data-volume:/var/lib/cassandra
    ports:
      - "9042:9042"
    restart: unless-stopped
    networks:
      - temporal-demo

  temporalfe:
    image: temporalio/server:${TMLTAG:-0.27.0}
    ports:
     - "7233:7233"
    environment:
      - "AUTO_SETUP=true"
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal-web:
    image: temporalio/web:${TWBTAG:-0.27.0}
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporalfe:7233"
    ports:
      - "8088:8088"
    depends_on:
      - temporalfe
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal-cli:
    image: temporalio/tctl:${TCLTAG:-0.27.0}
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporalfe:7233"
    depends_on:
      - temporalfe
    entrypoint: sh
    command: "-c 'while true; do sleep 5; done'"
    restart: unless-stopped
    networks:
      - temporal-demo

  temporal-acptstw:
    image: tlacptst:${TACTAG:-0.27.0}
    build:
      context: .
      dockerfile: Dockerfile_TLAcptst
    environment:
      - "TFEADDR=temporalfe"
    depends_on:
      - temporalfe
    entrypoint: dockerize -wait tcp://temporalfe:7233 worker
    restart: on-failure
    networks:
      - temporal-demo

  temporal-acptsts:
    image: tlacptst:${TACTAG:-0.27.0}
    build:
      context: .
      dockerfile: Dockerfile_TLAcptst
    environment:
      - "TFEADDR=temporalfe"
    depends_on:
      - temporalfe
      - temporal-acptstw
    entrypoint: starter
    restart: on-failure
    networks:
      - temporal-demo

volumes:
  data-volume:

networks:
  temporal-demo:
