version: '3.5'

services:

  monitoror:
    image: monitoror/monitoror:${MTRRTAG:-latest}
    volumes:
      - ../configs/monitoror/config.json:/etc/monitoror/config.json:ro
    ports:
     - "58888:8080"
    environment:
      - "MO_CONFIG=/etc/monitoror/config.json"
    restart: unless-stopped

networks:
  default:
    external:
      name: cldinabox-demo
