---
- name: render client monit config
  template: src="{{client_service}}.j2"
            dest="/etc/monit.d/{{client_service}}"
            owner="root"
            group="root"
  notify:
    - reload monit configs

- name: start and enable monit service
  service: name=monit
           state=started
           enabled=true
